### ISSUE TITLE
Add comments section to the blog

### ISSUE THREAD

**Issue by wsbctechnicalblog** [wsbctechnicalblog/wsbctechnicalblog.github.io#221]
I sometimes receive a comment on a blog post privately, after I share it on social media. It would be much better if we could enable moderated comments section for every post.

**Comment by wsbctechnicalblog** [comment]
@wpschaub, @erwsch1 another idea for the upcoming hackathon?

**Comment by wpschaub** [comment]
@wsbctechnicalblog agreed, please add it to the list of hackathon ideas document on our portal as well.

**Comment by wsbctechnicalblog** [comment]
@wpschaub Done

**Comment by wpschaub** [comment]
We have enabled comments, powered by Giscus!
