### ISSUE TITLE
Improve discoverability of hyperlinks

### ISSUE THREAD

**Issue by wpschaub** [wsbctechnicalblog/wsbctechnicalblog.github.io#259]
Hyperlinks are blending into the text, making them hard to discover. Can we change their style to blue and underlined?

![image](https://user-images.githubusercontent.com/12176555/145142686-c8f02ead-c47d-4873-8ba7-1ae18b18fb48.png)

**Comment by wsbctechnicalblog** [comment]
Modified links to be underlined. What I modified the colour to be blue, it messed up the blog post titles. May need a second opinion from the front-end UX specialist.

**Comment by wpschaub** [comment]
@wsbctechnicalblog thank you for the quick turnaround time. The current experience with the underline is perfect. Hyperlinks are now discoverable, yet they blend into the text - not creating lots of colour noise :)

**Comment by wsbctechnicalblog** [comment]
> @wsbctechnicalblog thank you for the quick turnaround time. The current experience with the underline is perfect. Hyperlinks are now discoverable, yet they blend into the text - not creating lots of colour noise :)

Thank you for the swift kick in the butt, @wpschaub. Those links were seriously bothering me for the longest time now, but always forgetting to attend to fixing them. Let's make our blog better and better!
